const fs = require('fs');
const path = require('path');

const projectRoot = path.resolve(__dirname, '..');
const dataDir = path.join(projectRoot, 'site', 'data');
const outputPath = path.join(dataDir, 'embedded-data.js');
const dataFiles = [
  'entity_list.csv',
  'monthly_operation.csv',
  'policy_briefing.csv',
  'budget_rules.csv',
  'budget_transfer.csv',
];

const payload = {};
for (const fileName of dataFiles) {
  const filePath = path.join(dataDir, fileName);
  payload[`data/${fileName}`] = fs.readFileSync(filePath, 'utf8');
}

const output = [
  '/* Auto-generated by delivery/build_embedded_data.js */',
  `globalThis.EMBEDDED_CSV_DATA = ${JSON.stringify(payload, null, 2)};`,
  '',
].join('\n');

fs.writeFileSync(outputPath, output, 'utf8');
console.log(`Wrote ${outputPath}`);