# coding: utf-8
"""Generate Module D: 2026 state-owned capital operating budget summary CSV."""
import csv, os

rows = [
    # --- RULE records (制度规则) ---
    {
        "record_id": "BDG-R-001",
        "record_type": "RULE",
        "scope": "central",
        "scope_label": "central_soe",
        "province": "",
        "rule_name": "central_profit_tier1",
        "rule_description": "Tier 1 resource-type SOEs (tobacco, oil/petrochemical, power, telecom, coal): taxed-profit collection ratio",
        "rule_description_zh": "第一类：烟草企业和石油石化、电力、电信、煤炭等资源型企业，税后利润收取比例",
        "ratio_value": "35%",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "2700.60",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "-5.4%",
        "notes": "2026 Tier-1 total income 2700.6 billion yuan"
    },
    {
        "record_id": "BDG-R-002",
        "record_type": "RULE",
        "scope": "central",
        "scope_label": "central_soe",
        "province": "",
        "rule_name": "central_profit_tier2",
        "rule_description": "Tier 2 general competitive SOEs (metals, transport, electronics, trade, construction): taxed-profit collection ratio",
        "rule_description_zh": "第二类：有色及黑色冶金采掘、运输、电子、贸易、施工等一般竞争型企业，税后利润收取比例",
        "ratio_value": "30%",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "633.17",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "-7.8%",
        "notes": "2026 Tier-2 total income 633.17 billion yuan"
    },
    {
        "record_id": "BDG-R-003",
        "record_type": "RULE",
        "scope": "central",
        "scope_label": "central_soe",
        "province": "",
        "rule_name": "central_profit_tier3",
        "rule_description": "Tier 3 military and research SOEs: taxed-profit collection ratio (source text truncated at fetch)",
        "rule_description_zh": "第三类：军工科研等企业，税后利润收取比例（原文抓取截断）",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S3",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Source text truncated after 'di-san-lei-wei-jun...'; historically 25% but NOT confirmed for 2026"
    },
    {
        "record_id": "BDG-R-004",
        "record_type": "RULE",
        "scope": "central",
        "scope_label": "central_soe",
        "province": "",
        "rule_name": "central_profit_tier4",
        "rule_description": "Tier 4 policy SOEs: taxed-profit collection ratio (source text truncated at fetch)",
        "rule_description_zh": "第四类：政策性企业等，税后利润收取比例（原文抓取截断）",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S3",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Source text truncated; historically 0% or minimal but NOT confirmed for 2026"
    },
    {
        "record_id": "BDG-R-005",
        "record_type": "RULE",
        "scope": "central",
        "scope_label": "central_budget",
        "province": "",
        "rule_name": "central_transfer_to_gpb",
        "rule_description": "Central SOE capital operating budget transfer amount to general public budget",
        "rule_description_zh": "中央国有资本经营预算调入一般公共预算金额",
        "ratio_value": "",
        "ratio_type": "transfer_to_gpb",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "2500.00",
        "budget_unit": "100M_CNY",
        "yoy": "+4.2%",
        "notes": "2025 execution: 2400 billion; 2026 budget: 2500 billion"
    },
    {
        "record_id": "BDG-R-006",
        "record_type": "RULE",
        "scope": "national",
        "scope_label": "national_total",
        "province": "",
        "rule_name": "national_transfer_to_gpb",
        "rule_description": "National total transfer from SOE capital operating budget to general public budget",
        "rule_description_zh": "全国国有资本经营预算调入一般公共预算合计",
        "ratio_value": "",
        "ratio_type": "transfer_to_gpb",
        "effective_year": "2026",
        "source_doc": "关于2025年中央和地方预算执行情况与2026年中央和地方预算草案的报告（摘要）",
        "source_url": "http://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260306_3984742.htm",
        "source_date": "2026-03-06",
        "evidence_strength": "S1",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "5304.88",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "National total, central + local"
    },
    # --- BUDGET FIGURE records (预算数字) ---
    {
        "record_id": "BDG-F-001",
        "record_type": "BUDGET_FIGURE",
        "scope": "central",
        "scope_label": "central_budget",
        "province": "",
        "rule_name": "",
        "rule_description": "Central SOE capital operating budget income",
        "rule_description_zh": "中央国有资本经营预算收入",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "3716.32",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "-4.8%",
        "notes": "Profit income 3522.33 + dividend 193.99; income total with carryover: 3976.23"
    },
    {
        "record_id": "BDG-F-002",
        "record_type": "BUDGET_FIGURE",
        "scope": "central",
        "scope_label": "central_budget",
        "province": "",
        "rule_name": "",
        "rule_description": "Central SOE capital operating budget expenditure",
        "rule_description_zh": "中央国有资本经营预算支出",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "关于2026年中央国有资本经营预算的说明",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985993.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "",
        "budget_expenditure": "1476.23",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "+13.8%",
        "notes": "Historical problems 73.17 + capital injection 766.17 + public welfare subsidy 636.89"
    },
    {
        "record_id": "BDG-F-003",
        "record_type": "BUDGET_FIGURE",
        "scope": "local",
        "scope_label": "local_aggregate",
        "province": "",
        "rule_name": "",
        "rule_description": "Local SOE capital operating budget income (aggregate of all provinces)",
        "rule_description_zh": "地方国有资本经营预算本级收入（全国地方合计）",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "关于2025年中央和地方预算执行情况与2026年中央和地方预算草案的报告（摘要）",
        "source_url": "http://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260306_3984742.htm",
        "source_date": "2026-03-06",
        "evidence_strength": "S1",
        "budget_income": "4249.82",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "-8.5%",
        "notes": "Decline mainly due to 2025 local SOE profit decline"
    },
    {
        "record_id": "BDG-F-004",
        "record_type": "BUDGET_FIGURE",
        "scope": "local",
        "scope_label": "local_aggregate",
        "province": "",
        "rule_name": "",
        "rule_description": "Local SOE capital operating budget expenditure (aggregate of all provinces)",
        "rule_description_zh": "地方国有资本经营预算支出（全国地方合计）",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "关于2025年中央和地方预算执行情况与2026年中央和地方预算草案的报告（摘要）",
        "source_url": "http://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260306_3984742.htm",
        "source_date": "2026-03-06",
        "evidence_strength": "S1",
        "budget_income": "",
        "budget_expenditure": "1478.72",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "+6.8%",
        "notes": ""
    },
    {
        "record_id": "BDG-F-005",
        "record_type": "BUDGET_FIGURE",
        "scope": "national",
        "scope_label": "national_total",
        "province": "",
        "rule_name": "",
        "rule_description": "National total SOE capital operating budget income",
        "rule_description_zh": "全国国有资本经营预算收入合计",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "预算草案报告（摘要）",
        "source_url": "http://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260306_3984742.htm",
        "source_date": "2026-03-06",
        "evidence_strength": "S1",
        "budget_income": "7966.14",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "-6.8%",
        "notes": "Central 3716.32 + Local 4249.82"
    },
    {
        "record_id": "BDG-F-006",
        "record_type": "BUDGET_FIGURE",
        "scope": "national",
        "scope_label": "national_total",
        "province": "",
        "rule_name": "",
        "rule_description": "National total SOE capital operating budget expenditure",
        "rule_description_zh": "全国国有资本经营预算支出合计",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "预算草案报告（摘要）",
        "source_url": "http://www.mof.gov.cn/zhengwuxinxi/caizhengxinwen/202603/t20260306_3984742.htm",
        "source_date": "2026-03-06",
        "evidence_strength": "S1",
        "budget_income": "",
        "budget_expenditure": "2921.17",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "+10.3%",
        "notes": ""
    },
    # --- TRANSFER records (central to local per province) ---
    {
        "record_id": "BDG-T-001",
        "record_type": "TRANSFER",
        "scope": "province",
        "scope_label": "central_to_local",
        "province": "guangdong",
        "rule_name": "",
        "rule_description": "Central->Guangdong SOE capital operating transfer payment",
        "rule_description_zh": "中央对广东省国有资本经营转移支付",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "2026年中央对地方国有资本经营转移支付分地区情况汇总表",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985992.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "0.75",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Incl. Shenzhen 0.03; ex-Shenzhen 0.72"
    },
    {
        "record_id": "BDG-T-002",
        "record_type": "TRANSFER",
        "scope": "province",
        "scope_label": "central_to_local",
        "province": "shandong",
        "rule_name": "",
        "rule_description": "Central->Shandong SOE capital operating transfer payment",
        "rule_description_zh": "中央对山东省国有资本经营转移支付",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "2026年中央对地方国有资本经营转移支付分地区情况汇总表",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985992.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "1.73",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Incl. Qingdao 0.13; ex-Qingdao 1.60"
    },
    {
        "record_id": "BDG-T-003",
        "record_type": "TRANSFER",
        "scope": "province",
        "scope_label": "central_to_local",
        "province": "zhejiang",
        "rule_name": "",
        "rule_description": "Central->Zhejiang SOE capital operating transfer payment",
        "rule_description_zh": "中央对浙江省国有资本经营转移支付",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "2026年中央对地方国有资本经营转移支付分地区情况汇总表",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985992.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "0.21",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Incl. Ningbo 0.03; ex-Ningbo 0.18"
    },
    {
        "record_id": "BDG-T-004",
        "record_type": "TRANSFER",
        "scope": "province",
        "scope_label": "central_to_local",
        "province": "sichuan",
        "rule_name": "",
        "rule_description": "Central->Sichuan SOE capital operating transfer payment",
        "rule_description_zh": "中央对四川省国有资本经营转移支付",
        "ratio_value": "",
        "ratio_type": "",
        "effective_year": "2026",
        "source_doc": "2026年中央对地方国有资本经营转移支付分地区情况汇总表",
        "source_url": "http://yss.mof.gov.cn/2026zyczys/202603/t20260324_3985992.htm",
        "source_date": "2026-03-24",
        "evidence_strength": "S1",
        "budget_income": "1.72",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": ""
    },
    # --- Provincial budget: NOT IDENTIFIED ---
    {
        "record_id": "BDG-P-001",
        "record_type": "BUDGET_FIGURE",
        "scope": "province",
        "scope_label": "province_level",
        "province": "guangdong",
        "rule_name": "",
        "rule_description": "Guangdong province-level SOE capital operating budget",
        "rule_description_zh": "广东省本级国有资本经营预算收支",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "",
        "source_url": "",
        "source_date": "",
        "evidence_strength": "S4",
        "budget_income": "UNIDENTIFIED",
        "budget_expenditure": "UNIDENTIFIED",
        "budget_transfer_to_gpb": "UNIDENTIFIED",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Provincial budget report is PDF only; finance department website returned 404/empty"
    },
    {
        "record_id": "BDG-P-002",
        "record_type": "BUDGET_FIGURE",
        "scope": "province",
        "scope_label": "province_level",
        "province": "shandong",
        "rule_name": "",
        "rule_description": "Shandong province-level SOE capital operating budget",
        "rule_description_zh": "山东省本级国有资本经营预算收支",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "关于山东省2025年预算执行情况与2026年预算草案的报告",
        "source_url": "http://czt.shandong.gov.cn/art/2026/2/13/art_10575_10329178.html",
        "source_date": "2026-02-13",
        "evidence_strength": "S4",
        "budget_income": "UNIDENTIFIED",
        "budget_expenditure": "UNIDENTIFIED",
        "budget_transfer_to_gpb": "UNIDENTIFIED",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Report exists as PDF download; text not extractable via web fetch"
    },
    {
        "record_id": "BDG-P-003",
        "record_type": "BUDGET_FIGURE",
        "scope": "province",
        "scope_label": "province_level",
        "province": "zhejiang",
        "rule_name": "",
        "rule_description": "Zhejiang province-level SOE capital operating budget",
        "rule_description_zh": "浙江省本级国有资本经营预算收支",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "",
        "source_url": "",
        "source_date": "",
        "evidence_strength": "S4",
        "budget_income": "UNIDENTIFIED",
        "budget_expenditure": "UNIDENTIFIED",
        "budget_transfer_to_gpb": "UNIDENTIFIED",
        "budget_unit": "100M_CNY",
        "yoy": "",
        "notes": "Provincial budget not found in HTML; finance dept homepage does not link to budget text"
    },
    {
        "record_id": "BDG-P-004",
        "record_type": "RULE",
        "scope": "province",
        "scope_label": "province_level",
        "province": "ALL",
        "rule_name": "local_profit_ratio",
        "rule_description": "Provincial SOE net profit collection ratios",
        "rule_description_zh": "各省国有企业净利润上缴比例规则",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "net_profit_collection",
        "effective_year": "2026",
        "source_doc": "",
        "source_url": "",
        "source_date": "",
        "evidence_strength": "S4",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "",
        "yoy": "",
        "notes": "Provincial ratios are in local implementation rules (地方办法), not in budget reports; not accessible via HTML fetch"
    },
    {
        "record_id": "BDG-P-005",
        "record_type": "RULE",
        "scope": "province",
        "scope_label": "province_level",
        "province": "ALL",
        "rule_name": "local_transfer_to_gpb_ratio",
        "rule_description": "Provincial SOE capital budget transfer to general public budget ratio",
        "rule_description_zh": "各省国有资本经营预算划入一般公共预算比例",
        "ratio_value": "UNIDENTIFIED",
        "ratio_type": "transfer_to_gpb",
        "effective_year": "2026",
        "source_doc": "",
        "source_url": "",
        "source_date": "",
        "evidence_strength": "S4",
        "budget_income": "",
        "budget_expenditure": "",
        "budget_transfer_to_gpb": "",
        "budget_unit": "",
        "yoy": "",
        "notes": "Not found in any publicly accessible HTML page; may require PDF parsing of provincial budget reports"
    },
]

fields = [
    "record_id", "record_type", "scope", "scope_label", "province",
    "rule_name", "rule_description", "rule_description_zh",
    "ratio_value", "ratio_type", "effective_year",
    "source_doc", "source_url", "source_date", "evidence_strength",
    "budget_income", "budget_expenditure", "budget_transfer_to_gpb",
    "budget_unit", "yoy", "notes"
]

out_dir = r"C:\Users\ASUS\guozi_skill_prep\delivery"
csv_path = os.path.join(out_dir, "guozi_budget_rules_v1_20260402.csv")

with open(csv_path, "w", newline="", encoding="utf-8-sig") as f:
    w = csv.DictWriter(f, fieldnames=fields)
    w.writeheader()
    w.writerows(rows)

print(f"Written {len(rows)} records to {csv_path}")

# Also write the full transfer table as a separate reference CSV
transfer_data = [
    ("beijing", 0.95, 0.95),
    ("tianjin", 0.43, 0.43),
    ("hebei", 1.97, 1.89),
    ("shanxi", 2.45, 2.45),
    ("inner_mongolia", 0.72, 0.72),
    ("liaoning", 2.55, 2.55),
    ("jilin", 1.06, 1.06),
    ("heilongjiang", 3.93, 3.93),
    ("shanghai", 0.93, 0.93),
    ("jiangsu", 0.68, 0.68),
    ("zhejiang", 0.21, 0.21),
    ("anhui", 0.88, 0.88),
    ("fujian", 0.20, 0.20),
    ("jiangxi", 0.67, 0.67),
    ("shandong", 1.73, 1.73),
    ("henan", 2.58, 2.58),
    ("hubei", 1.84, 1.84),
    ("hunan", 0.99, 0.99),
    ("guangdong", 0.75, 0.75),
    ("guangxi", 0.33, 0.33),
    ("hainan", 0.04, 0.04),
    ("chongqing", 0.60, 0.60),
    ("sichuan", 1.72, 1.72),
    ("guizhou", 0.83, 0.83),
    ("yunnan", 0.73, 0.73),
    ("tibet", 0.01, 0.01),
    ("shaanxi", 2.02, 2.02),
    ("gansu", 0.91, 0.91),
    ("qinghai", 0.21, 0.21),
    ("ningxia", 0.24, 0.24),
    ("xinjiang", 0.70, 0.70),
]

transfer_path = os.path.join(out_dir, "guozi_budget_transfer_by_province_v1_20260402.csv")
with open(transfer_path, "w", newline="", encoding="utf-8-sig") as f:
    w = csv.writer(f)
    w.writerow(["province", "2025_execution_100M_CNY", "2026_budget_100M_CNY"])
    for row in transfer_data:
        w.writerow(row)

print(f"Written {len(transfer_data)} province transfer records to {transfer_path}")
